kind: pipeline
name: default
steps:
- name: test
  image: golang:1.14
  commands:
  - go test -v -cover ./pkg/...
- name: frontend
  image: node:12
  commands:
  - cd frontend
  - yarn install
  - yarn build
- name: docker
  image: plugins/docker
  settings:
    repo: nsmith5/talaria
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
  when:
    branch:
    - master
